site_name: Jie的量化学习笔记
site_description: Jie的 Freqtrade 量化交易学习笔记，从零开始的量化交易之旅
site_author: Jie

theme:
  name: readthedocs
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - 首页: index.md
  - 配置详解: 01-配置文件详解.md
  - 回测指南: 02-回测结果解读指南.md
  - 交易术语: 03-金融交易术语详解.md
  - 命令手册: 04-Freqtrade命令手册.md

dev_addr: 10.24.32.125:8000

# 插件配置
plugins:
  - search:
      lang: zh

# 额外配置
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/freqtrade/freqtrade

copyright: Copyright &copy; 2025 Jie的量化学习笔记